"""Python arithmetic:
    basic operators: + - * / %
    plus. minus, times, divided by, modulus ** EXPONENTIAL
"""
a = 2
b=3
c=4
print ('a,b,c are:',a,b,c)
print('a + b = ',a+b)
print('c - b is',c-b)
print('c / a is',c/a, 'note that the result is floating point - all division is')
print ('the remainder of c / b ...c%b is',c%b)


string formatting:
>>> x="Dear %s %s, you have $%f in your account."%('Dave','Britton',500)
>>> x
'Dear Dave Britton, you have $500.000000 in your account.'
>>> x="Dear %s %s, you have $%f in your account."%('Dave','Britton',500.01)
>>> x
'Dear Dave Britton, you have $500.010000 in your account.'
>>> x="Dear %s %s, you have $%6.2f in your account."%('Dave','Britton',500.01)
>>> x
'Dear Dave Britton, you have $500.01 in your account.'
>>> x="Dear %s %s, you have $%d in your account."%('Dave','Britton',500.01)
>>> x
'Dear Dave Britton, you have $500 in your account.'
>>>     
"""
The csv module: (python docs:) 14.1. csv — CSV File Reading and Writing

The so-called CSV (Comma Separated Values) format is the most common
import and export format for spreadsheets and databases. CSV format was
used for many years prior to attempts to describe the format in a
standardized way in RFC 4180. The lack of a well-defined standard means
that subtle differences often exist in the data produced and consumed by
different applications. These differences can make it annoying to
process CSV files from multiple sources. Still, while the delimiters and
quoting characters vary, the overall format is similar enough that it is
possible to write a single module which can efficiently manipulate such
data, hiding the details of reading and writing the data from the
programmer.

The csv module implements classes to read and write tabular data in CSV
format. It allows programmers to say, “write this data in the format
preferred by Excel,” or “read data from this file which was generated by
Excel,” without knowing the precise details of the CSV format used by
Excel. Programmers can also describe the CSV formats understood by other
applications or define their own special-purpose CSV formats.

The csv module’s reader and writer objects read and write sequences.
Programmers can also read and write data in dictionary form using the
DictReader and DictWriter classes.

    

#
